using System.Xml;
using System.Xml.Linq;
using System.IO;
namespace DataProcessor
{
    class Processor
    {
        static string PrimaryDOIElementFileName = "primary_doi_elements.jsonl";
        static string SecondaryDOIElementFileName = "secondary_doi_elements.jsonl";
        static string SecondaryDOIListFileName = "secondary_doi.csv";

        static string ModifiedPrimaryDOIElementFileName = "modified_primary_doi_elements.jsonl";
        static string ModifiedSecondaryDOIElementFileName = "modified_secondary_doi_elements.jsonl";


        public static void BuildTagCSVFromDataCite(DBLPOptions opts)
        {
            OutputSystemMessageFunction("Building DataCite subjects");
            var foundJSONLMapFilePath = DataCiteFoundDOICache.GetCachePath(opts.DataFolderPath);
            Dictionary<string, string> foundJSONLMap = DataCiteJSONLLoader.Load(foundJSONLMapFilePath);
            Console.WriteLine("Found JSONL Map: " + foundJSONLMap.Count);

            List<string> csvLines = new List<string>();

            foundJSONLMap.Keys.ToList().ForEach((v) =>
            {
                var tags = DOIElement.GetTagsFromDataCiteJSONL(foundJSONLMap[v]);
                if (tags.Count > 0)
                {
                    List<string> line = new List<string>();
                    line.Add(v);
                    tags.ForEach((tag) => line.Add(tag));
                    csvLines.Add(string.Join('\t', line));
                }
            });


            var folderPath = opts.DataFolderPath + "/raw/user_files/DataCite";
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }

            CSVFunctions.WriteCSV(folderPath + "/tag.tsv", csvLines);
            OutputSystemMessageFunction("Saved: " + folderPath + "/tag.tsv");

        }

        public static void BuildBigCache(DBLPOptions opts)
        {
            CrossRefPreprocessor.BuildBigCache(opts.DataFolderPath);
            DataCitePreprocessor.BuildBigCache(opts.DataFolderPath);

        }


        public static async Task<int> BuildSmallCacheForPrimaryDOIElements(DBLPOptions opts)
        {
            var UrlPath = GetFilePathInAutoGeneratedFolder(opts.DataFolderPath, "url.csv");
            var TagPath = GetFilePathInAutoGeneratedFolder(opts.DataFolderPath, "tag.csv");

            OutputSystemMessageFunction("Creating DOI to Tag Mapper");
            var doiToTagMapper = DoiToTagMapper.CreateDoiToTagMapper(UrlPath, TagPath);
            var primaryDOISet = new HashSet<string>(doiToTagMapper.Keys);

            OutputSystemMessageFunction("Building cache for primary DOI elements");
            await DOIElementPreprocessor.BuildSmallCache(opts.DataFolderPath, opts.MailAddress, primaryDOISet);

            return 0;
        }
        public static void BuildPrimaryDOIElementDictionary(DBLPOptions opts)
        {
            var UrlPath = GetFilePathInAutoGeneratedFolder(opts.DataFolderPath, "url.csv");
            var TagPath = GetFilePathInAutoGeneratedFolder(opts.DataFolderPath, "tag.csv");

            OutputSystemMessageFunction("Creating DOI to Tag Mapper");
            var doiToTagMapper = DoiToTagMapper.CreateDoiToTagMapper(UrlPath, TagPath);
            var primaryDOISet = new HashSet<string>(doiToTagMapper.Keys);

            OutputSystemMessageFunction("Building primary DOI element dictionary");
            var primaryDOIElementDict = DOIElementPreprocessor.BuildDOIElementDictionary(opts.DataFolderPath, primaryDOISet);

            OutputSystemMessageFunction("Saving primary DOI element dictionary to: " + GetFilePathInResultFolder(opts.DataFolderPath, PrimaryDOIElementFileName));
            DOIElement.Save(primaryDOIElementDict, GetFilePathInResultFolder(opts.DataFolderPath, PrimaryDOIElementFileName));

        }
        public static async Task<int> BuildSmallCacheForSecondaryDOIElements(DBLPOptions opts)
        {
            var UrlPath = GetFilePathInAutoGeneratedFolder(opts.DataFolderPath, "url.csv");
            var TagPath = GetFilePathInAutoGeneratedFolder(opts.DataFolderPath, "tag.csv");

            OutputSystemMessageFunction("Creating DOI to Tag Mapper");
            var doiToTagMapper = DoiToTagMapper.CreateDoiToTagMapper(UrlPath, TagPath);
            var primaryDOISet = new HashSet<string>(doiToTagMapper.Keys);


            OutputSystemMessageFunction("Loading primary DOI element dictionary");
            var primaryDOIElementDict = DOIElement.Load(GetFilePathInResultFolder(opts.DataFolderPath, PrimaryDOIElementFileName), true);


            OutputSystemMessageFunction("Building secondary DOI set");
            var secondaryDOISet = new HashSet<string>();
            primaryDOIElementDict.Values.ToList().ForEach((v) =>
            {
                v.DOIReferences.ForEach((referenceDOI) =>
                {
                    if (!doiToTagMapper.ContainsKey(referenceDOI))
                    {
                        secondaryDOISet.Add(referenceDOI);
                    }
                });
            });

            OutputSystemMessageFunction("Building cache for secondary DOI set");
            await DOIElementPreprocessor.BuildSmallCache(opts.DataFolderPath, opts.MailAddress, secondaryDOISet);

            return 0;
        }

        public static void BuildSecondaryDOIElementDictionary(DBLPOptions opts)
        {
            var UrlPath = GetFilePathInAutoGeneratedFolder(opts.DataFolderPath, "url.csv");
            var TagPath = GetFilePathInAutoGeneratedFolder(opts.DataFolderPath, "tag.csv");

            OutputSystemMessageFunction("Creating DOI to Tag Mapper");
            var doiToTagMapper = DoiToTagMapper.CreateDoiToTagMapper(UrlPath, TagPath);
            var primaryDOISet = new HashSet<string>(doiToTagMapper.Keys);

            OutputSystemMessageFunction("Loading primary DOI element dictionary");
            var primaryDOIElementDict = DOIElement.Load(GetFilePathInResultFolder(opts.DataFolderPath, PrimaryDOIElementFileName), true);

            OutputSystemMessageFunction("Building secondary DOI set");
            var secondaryDOISet = new HashSet<string>();
            primaryDOIElementDict.Values.ToList().ForEach((v) =>
            {
                v.DOIReferences.ForEach((referenceDOI) =>
                {
                    if (!doiToTagMapper.ContainsKey(referenceDOI))
                    {
                        secondaryDOISet.Add(referenceDOI);
                    }
                });
            });

            OutputSystemMessageFunction("Building secondary DOI element dictionary");
            var secondaryDOIElementDict = DOIElementPreprocessor.BuildDOIElementDictionary(opts.DataFolderPath, secondaryDOISet);

            OutputSystemMessageFunction("Saving secondary DOI element dictionary to: " + GetFilePathInResultFolder(opts.DataFolderPath, SecondaryDOIElementFileName));
            DOIElement.Save(secondaryDOIElementDict, GetFilePathInResultFolder(opts.DataFolderPath, SecondaryDOIElementFileName));

            OutputSystemMessageFunction("Saving secondary DOI list to: " + GetFilePathInResultFolder(opts.DataFolderPath, SecondaryDOIListFileName));
            var secondaryDOIList = secondaryDOISet.ToList();
            secondaryDOIList.Sort();
            CSVFunctions.WriteCSV(GetFilePathInResultFolder(opts.DataFolderPath, SecondaryDOIListFileName), secondaryDOIList);

        }



        public static void OutputSystemMessageFunction(string message)
        {
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.WriteLine(message);
            Console.ResetColor();
        }

        public static string GetFilePathInResultFolder(string dataFolderPath, string filename)
        {
            var resultFolderPath = dataFolderPath + "/auto_generated/result";
            if (!Directory.Exists(resultFolderPath))
            {
                Directory.CreateDirectory(resultFolderPath);
            }


            return dataFolderPath + "/auto_generated/result/" + filename;
        }
        public static string GetFilePathInAutoGeneratedFolder(string dataFolderPath, string filename)
        {
            var autoGeneratedFolderPath = dataFolderPath + "/auto_generated";
            if (!Directory.Exists(autoGeneratedFolderPath))
            {
                Directory.CreateDirectory(autoGeneratedFolderPath);
            }

            return dataFolderPath + "/auto_generated/" + filename;
        }

        public static int CreateLightweightDOIInfoFolder(DBLPOptions opts)
        {
            OutputSystemMessageFunction("Process: CreateLightweightDOIInfoFolder[Start]");

            var primaryDOIElementDict = DOIElement.Load(GetFilePathInResultFolder(opts.DataFolderPath, ModifiedPrimaryDOIElementFileName), true);
            var secondaryDOIElementDict = DOIElement.Load(GetFilePathInResultFolder(opts.DataFolderPath, ModifiedSecondaryDOIElementFileName), true);
            OutputSystemMessageFunction("Building lightweight DOI element component");
            var lightweightDOIElementComponent = LightweightDOIElementComponent.Build(primaryDOIElementDict, secondaryDOIElementDict);

            OutputSystemMessageFunction("Saving lightweight DOI element component to: " + GetFilePathInResultFolder(opts.DataFolderPath, "lightweight_doi_info"));
            lightweightDOIElementComponent.OutputByGZip(GetFilePathInResultFolder(opts.DataFolderPath, "lightweight_doi_info"));

            OutputSystemMessageFunction("Process: CreateLightweightDOIInfoFolder[End]");

            return 0;
        }

        public static int ModifyDOIElementDictionary(DBLPOptions opts)
        {

            OutputSystemMessageFunction("Running doi_processor");

            var primaryDOIElementDict = DOIElement.Load(GetFilePathInResultFolder(opts.DataFolderPath, PrimaryDOIElementFileName), true);
            var secondaryDOIElementDict = DOIElement.Load(GetFilePathInResultFolder(opts.DataFolderPath, SecondaryDOIElementFileName), true);

            OutputSystemMessageFunction("Modifying container title using DBLP summary");
            ReplacementRules.ReplaceContainerTitleUsingDBLPSummary(GetFilePathInResultFolder(opts.DataFolderPath, "dblp_proceedings.jsonl"), primaryDOIElementDict, secondaryDOIElementDict);


            OutputSystemMessageFunction("Normalizing container title");
            ContainerTitleNormalization.NormalizeDOIElementDictionary(primaryDOIElementDict);
            ContainerTitleNormalization.NormalizeDOIElementDictionary(secondaryDOIElementDict);


            OutputSystemMessageFunction("Applying type replacement rules");
            ReplacementRules.ReplaceType(opts.DataFolderPath + "/raw/doi_processor/type_replacement_rules.tsv", primaryDOIElementDict, secondaryDOIElementDict);

            OutputSystemMessageFunction("Applying container-title replacement rules");
            ReplacementRules.ReplaceContainerTitle(opts.DataFolderPath + "/raw/doi_processor/container_title_replacement_rules.tsv", primaryDOIElementDict, secondaryDOIElementDict);

            OutputSystemMessageFunction("Modifying container title by DOI prefix");
            ReplacementRules.ReplaceContainerTitleByDOIPrefix(opts.DataFolderPath + "/raw/doi_processor/doi_prefix_key_container_title_value.tsv", primaryDOIElementDict, secondaryDOIElementDict);

            OutputSystemMessageFunction("Modifying type by DOI prefix");
            ReplacementRules.ReplaceTypeByDOIPrefix(opts.DataFolderPath + "/raw/doi_processor/doi_prefix_key_type_value.tsv", primaryDOIElementDict, secondaryDOIElementDict);

            OutputSystemMessageFunction("Saving primary DOI element dictionary to: " + GetFilePathInResultFolder(opts.DataFolderPath, ModifiedPrimaryDOIElementFileName));
            DOIElement.Save(primaryDOIElementDict, GetFilePathInResultFolder(opts.DataFolderPath, ModifiedPrimaryDOIElementFileName));

            OutputSystemMessageFunction("Saving secondary DOI element dictionary to: " + GetFilePathInResultFolder(opts.DataFolderPath, ModifiedSecondaryDOIElementFileName));
            DOIElement.Save(secondaryDOIElementDict, GetFilePathInResultFolder(opts.DataFolderPath, ModifiedSecondaryDOIElementFileName));

            OutputSystemMessageFunction("doi_processor is finished");


            return 0;
        }

    }
}
